name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  verify:
    name: Verify Project Structure
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      
    - name: Make script executable
      run: chmod +x ci/run_and_check.sh
      
    - name: Run verification script
      run: ./ci/run_and_check.sh
